### PR TITLE
Charts are sized automatically by their container

### PR DESCRIPTION
**Pull request by jrjohnson**
Detects the size of the component and sizes the charts appropriately
instead of needing to pass in the width/height directly.

Closes #14 
Closes #15

### CODE REVIEW

**Comment by gabycampagna** [comment]
**When first loading the charts look good:**

screen shot 2017-07-05 at 1 22 12 pm


**This is how they rend when the browser is minimized**
screen shot 2017-07-05 at 1 21 16 pm

Not sure if you are seeing the same issue. I can play around with this. 

Couple of questions:
Would you like me to add CSS styling for the links?    If so should I branch off of yours before we merge?

2. CSS grid could work nicely to on the chart pages. I can add new CSS grid layout for them.

3. Perhaps I can add an Ember and D3 icons in the right side in the header for decoration?

**Comment by jrjohnson** [comment]
I am seeing that. Plus I'm seeing an issue with ember-resize and getting tests to pass. I hope to pick this back up for some work early next week, if you want to branch and change feel free, I won't be getting back to this before the weekend for sure.

**Comment by gabycampagna** [comment]
I will branch from this branch and play around with this by adding some styles and fixing the layout for the donut-chart page.  Thanks for the quick response!

**Comment by jrjohnson** [comment]
I think the double chart deal is caused by something wrong with the way we keep appending `g`s. It looks like an extra one gets added. I'm guessing we need a `selectAll` in there somewhere. I'm trying some stuff out now - but wanted to check in case you had already solved it.

**Comment by gabycampagna** [comment]
I haven't had a chance to look into the fix yet...Was totally sided tracked with other things. Sorry about that. Go ahead and see if that works..thx

**Comment by jrjohnson** [comment]
Well good news and bad news, the good news is I have figured out how to scale the `svg` to fill the containing element automatically and also re-draw then that element changes size. The bad news is it kind of messes with things like axis and labels (or at least I haven't quite figured out how to put them back).

Bar chart and pie chart now resize with the container, give them a look.

**Comment by gabycampagna** [comment]
Oh, I see.. Did you get a chance to look at the PR I opened? We need to 'redraw' the svg and that is why it is duplicating.

**Comment by jrjohnson** [comment]
Yes, and I guess great minds think alike. That is exactly what I ended up doing in the new chart properties mixin. The only difference is that I first calculate if the size of the SVG itself has changed. Otherwise it re-draws way too often.

**Comment by gabycampagna** [comment]
Wow!  Pretty nice!

**Pull request merged**
