### PR TITLE
Convert to monorepo

### LINKED ISSUE #877: Switch to v2 Addon (and maybe a monorepo)
Placeholder ticket. Up for grabs.

### LINKED ISSUE #929: Docs site is not rendering
https://ember-simple-charts.netlify.com/ 😢

### PR DESCRIPTION
**Pull request by jrjohnson**
Extracted test-app and docs into their owns apps and focused the add-on on just what it needs. Hopefully this fixes #929.

Closed #877 #943 

Once this is merged we'll have to fix our netlify build to do the right thing, so those tests will fail here.

### CODE REVIEW

**Review by stopfstedt — CHANGES_REQUESTED** [review]
the package lock file needs to be regenerated again and re-committed.
otherwise, this looks great!

**Comment by jrjohnson** [comment]
Done and pushed.

**Comment by stopfstedt** [comment]
> Done and pushed.

Thanks. Still getting an updated lock file when running `npm install`, but down to one discrepancy.

```diff
diff --git a/package-lock.json b/package-lock.json
index beee6bab..50f8375d 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,5 +1,5 @@
 {
-  "name": "simple-charts",
+  "name": "ember-simple-charts",
   "lockfileVersion": 2,
   "requires": true,
   "packages": {
```

Any idea how to shake this? I'm running on npm/node v8.5.5/v16.15.0.

**Comment by jrjohnson** [comment]
Sorted! Turns out if there is no name npm just picks the directory name and I have mine in a `simple-charts` folder. I added a name at the top level and this should now be ready.

**Review by stopfstedt — APPROVED** [review]

**Pull request merged**
